#!/bin/bash
# if i'm on the laptop, eDP-1 is the mainMonitor
# if i'm on the desktop, DP-2 is the mainMonitor
#
# other monitors are present, the external monitor becomes the mainMonitor and the previous mainMonitor becomes the secondaryMonitor
#
# Use hyprctl monitors to get the names
#
# write the output in ~/.config/hypr/custom/monitor.lua where it just return the object monitors that i can use in other files

OUT_DIR="$HOME/.config/hypr/custom"
OUT_FILE="$OUT_DIR/monitor.lua"

mkdir -p "$OUT_DIR"

# Names of every currently connected monitor
mapfile -t MONITORS < <(hyprctl monitors -j | jq -r '.[].name')

# Pick the built-in monitor depending on which machine we're on
baseMonitor=""
for name in "${MONITORS[@]}"; do
  if [[ "$name" == "eDP-1" || "$name" == "DP-2" ]]; then
    baseMonitor="$name"
    break
  fi
done

# Fall back to the first monitor reported if neither of the known names is present
if [[ -z "$baseMonitor" ]]; then
  baseMonitor="${MONITORS[0]}"
fi

# Any monitor that isn't the base one is considered "external"
externalMonitor=""
for name in "${MONITORS[@]}"; do
  if [[ "$name" != "$baseMonitor" ]]; then
    externalMonitor="$name"
    break
  fi
done

if [[ -n "$externalMonitor" ]]; then
  if [[ "$baseMonitor" == "eDP-1" ]]; then
    # Laptop: an external monitor takes over as mainMonitor, the laptop
    # panel becomes the secondary one
    mainMonitor="$externalMonitor"
    secondaryMonitor="$baseMonitor"
  else
    # Desktop: DP-2 stays the mainMonitor, the external one is secondary
    mainMonitor="$baseMonitor"
    secondaryMonitor="$externalMonitor"
  fi
else
  mainMonitor="$baseMonitor"
  secondaryMonitor="$baseMonitor"
fi

cat > "$OUT_FILE" <<EOF
-- Auto-generated by scripts/configMonitors.sh, do not edit by hand
return {
  mainMonitor = "$mainMonitor",
  secondaryMonitor = "$secondaryMonitor",
}
EOF
